pipeline {
    agent any
    stages {
        stage('Sonar Analysis') {
            steps {
                echo 'Testing..'
                sh 'cd webapp && sudo docker run  --rm -e SONAR_HOST_URL="http://35.154.75.206:9000" -e SONAR_LOGIN="sqp_7d94b177a5fc6764ffe9bf74c26ce180dcfb41b4"  -v ".:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=lms-project'
            }
        }
        stage('Build LMS') {
            steps {
                echo 'Building..'
                sh 'cd webapp && npm install && npm run build'
            }
        }
        stage('Release LMS') {
            steps {
                script {
                    echo "Releasing.."
                    def packageJSON = readJSON file: 'webapp/package.json'
                    def packageJSONVersion = packageJSON.version
                    echo "${packageJSONVersion}"
                    sh "zip webapp/dist-${packageJSONVersion}.zip -r webapp/dist"
                    sh "curl -v -u admin:renuka --upload-file webapp/dist-${packageJSONVersion}.zip http://35.154.75.206:8081/repository/lmsproject/"
            }
            }
        }
        stage('Deploy LMS') {
            steps {
                script {
                    echo "Deploying.."
                    def packageJSON = readJSON file: 'webapp/package.json'
                    def packageJSONVersion = packageJSON.version
                    echo "${packageJSONVersion}"
                    sh "curl -u admin:renuka -X GET \'http://35.154.75.206:8081/repository/lmsproject/dist-${packageJSONVersion}.zip\' --output dist-'${packageJSONVersion}'.zip"
                
                    sh 'sudo rm -rf /var/www/html/*'
                    sh "sudo unzip -o dist-'${packageJSONVersion}'.zip"
                    sh "sudo cp -r webapp/dist/* /var/www/html/"
                

            }
            }
        }
    }
}
